import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="fixed top-0 inset-x-0 z-50 border-b border-black/[.08] dark:border-white/[.12] bg-background/70 backdrop-blur supports-[backdrop-filter]:bg-background/60">
          <div className="mx-auto max-w-6xl px-4 sm:px-6 h-16 flex items-center justify-between">
            <div className="text-lg font-semibold tracking-tight">Scheduly</div>
            <nav className="flex items-center gap-3">
              <a
                href="/login"
                className="h-9 px-4 rounded-full border border-black/[.12] dark:border-white/[.18] text-sm hover:bg-black/[.04] dark:hover:bg-white/[.06] transition-colors"
              >
                Login
              </a>
              <a
                href="/get-started"
                className="h-9 px-4 rounded-full bg-foreground text-background text-sm font-medium hover:opacity-90 transition-opacity"
              >
                Get started
              </a>
            </nav>
          </div>
        </header>
        <main className="pt-16">{children}</main>
      </body>
    </html>
  );
}
